--
-- PostgreSQL database dump
--

\restrict rNREQXNhfBoDOwk8bE8Fm5xNfanCb60wPSevDORxiyAqchmCNycbuX2fpyYkjjs

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: action_items; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.action_items (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    due_date date,
    owner_email character varying(255) NOT NULL,
    status character varying(255),
    task text NOT NULL,
    meeting_id bigint,
    CONSTRAINT action_items_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.action_items OWNER TO admin;

--
-- Name: action_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.action_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.action_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_insights; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.meeting_insights (
    id bigint NOT NULL,
    analyzed_at timestamp(6) without time zone NOT NULL,
    decisions text,
    raw_ai_response text,
    summary text,
    meeting_id bigint
);


ALTER TABLE public.meeting_insights OWNER TO admin;

--
-- Name: meeting_insights_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.meeting_insights ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_insights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_participant_names; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.meeting_participant_names (
    meeting_id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.meeting_participant_names OWNER TO admin;

--
-- Name: meeting_participants; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.meeting_participants (
    meeting_id bigint NOT NULL,
    email character varying(255)
);


ALTER TABLE public.meeting_participants OWNER TO admin;

--
-- Name: meetings; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.meetings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    meeting_date timestamp(6) without time zone NOT NULL,
    status character varying(255),
    title character varying(255) NOT NULL,
    transcript text,
    created_by bigint,
    CONSTRAINT meetings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ANALYZED'::character varying])::text[])))
);


ALTER TABLE public.meetings OWNER TO admin;

--
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    is_approved boolean DEFAULT false,
    role character varying(255) DEFAULT 'user'::character varying
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: action_items; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.action_items (id, completed_at, created_at, due_date, owner_email, status, task, meeting_id) FROM stdin;
1	\N	2026-04-16 17:37:07.00878	2026-04-20	Bob	PENDING	Prepare financial report	9
2	\N	2026-04-16 17:37:07.065785	2026-04-18	Alice	PENDING	Send client proposal	9
3	\N	2026-04-16 18:01:29.199132	2026-04-20	Bob	PENDING	Prepare financial report	10
4	\N	2026-04-16 18:01:29.213825	2026-04-18	Alice	PENDING	Send client proposal	10
5	\N	2026-04-16 18:08:30.334225	2026-04-20	Bob	PENDING	Prepare financial report	11
6	\N	2026-04-16 18:08:30.351082	2026-04-18	Alice	PENDING	Send client proposal	11
7	\N	2026-04-16 18:14:53.4005	2026-04-20	Bob	PENDING	Prepare financial report	12
8	\N	2026-04-16 18:14:53.416061	2026-04-18	Alice	PENDING	Send client proposal	12
9	\N	2026-04-16 18:19:06.124141	2026-04-20	Bob	PENDING	Prepare financial report	13
10	\N	2026-04-16 18:19:06.139193	2026-04-18	Alice	PENDING	Send client proposal	13
42	\N	2026-04-18 15:44:40.271799	2026-04-20	Bob	PENDING	Prepare financial report	46
43	\N	2026-04-18 15:44:40.286667	2026-04-18	Alice	PENDING	Send client proposal	46
44	\N	2026-04-18 15:48:55.151769	2024-04-20	Bob	PENDING	Prepare financial report	47
45	\N	2026-04-18 15:48:55.160239	2024-04-18	Alice	PENDING	Send client proposal	47
46	\N	2026-04-18 15:56:25.797769	2026-04-20	Bob	PENDING	Prepare financial report	48
47	\N	2026-04-18 15:56:25.815106	2026-04-18	Alice	PENDING	Send client proposal	48
48	\N	2026-04-18 16:01:55.668677	2026-04-25	Alice	PENDING	Prepare budget report	49
49	\N	2026-04-18 16:01:55.696051	2026-04-22	Bob	PENDING	Send client proposal	49
50	\N	2026-04-18 16:07:45.383545	2026-04-25	Alice	PENDING	Prepare budget report	50
51	\N	2026-04-18 16:07:45.400719	2026-04-22	Bob	PENDING	Send client proposal	50
52	\N	2026-04-18 16:13:03.346356	2026-04-25	Alice	PENDING	Prepare budget report	51
53	\N	2026-04-18 16:13:03.373438	2026-04-22	Bob	PENDING	Send client proposal	51
54	\N	2026-04-18 16:21:43.707999	2026-04-25	Alice	PENDING	Prepare budget report	52
55	\N	2026-04-18 16:21:43.722577	2026-04-22	Bob	PENDING	Send client proposal	52
56	\N	2026-04-18 16:27:38.270532	2026-04-25	Alice	PENDING	Prepare budget report	53
57	\N	2026-04-18 16:27:38.289151	2026-04-22	Bob	PENDING	Send client proposal	53
58	\N	2026-04-18 17:37:42.162244	2026-04-25	Alice	PENDING	Prepare budget report	54
59	2026-04-18 17:39:30.47045	2026-04-18 17:37:42.179502	2026-04-22	Bob	DONE	Send client proposal	54
60	\N	2026-07-28 19:13:15.877742	2026-07-29	Ankit	PENDING	Complete project documentation	58
61	\N	2026-07-28 19:18:52.369969	2026-07-29	ankitp12160@gmail.com	PENDING	Complete project documentation	59
62	\N	2026-07-28 19:42:20.399454	2026-07-29	ankitp12160@gmail.com	PENDING	Complete frontend	60
85	2026-09-13 20:37:50.204294	2026-09-13 20:35:17.82498	2026-09-15	ankitchirag2003@gmail.com	DONE	review the code	72
90	\N	2026-09-23 21:29:32.056262	2026-09-25	chiragpokhariya2003@gmail.com	PENDING	Fix notification service and deploy patch	74
91	\N	2026-09-23 21:29:32.06532	2026-09-25	ankitchirag2003@gmail.com	PENDING	Write post‑incident report documenting root cause	74
\.


--
-- Data for Name: meeting_insights; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.meeting_insights (id, analyzed_at, decisions, raw_ai_response, summary, meeting_id) FROM stdin;
1	2026-04-16 17:37:07.084319	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	9
2	2026-04-16 18:01:29.224958	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	10
3	2026-04-16 18:08:30.360996		{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	11
4	2026-04-16 18:14:53.426026	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	12
5	2026-04-16 18:19:06.1482	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	13
38	2026-04-18 15:44:40.298698	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	46
39	2026-04-18 15:48:55.169389	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2024-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2024-04-18"}]}	Discussion of Q4 budget and tasks	47
40	2026-04-18 15:56:25.824939	["Increase marketing spend"]	{"summary": "Discussion of Q4 budget and tasks", "decisions": ["Increase marketing spend"], "actionItems": [{"task": "Prepare financial report", "owner": "Bob", "dueDate": "2026-04-20"}, {"task": "Send client proposal", "owner": "Alice", "dueDate": "2026-04-18"}]}	Discussion of Q4 budget and tasks	48
41	2026-04-18 16:01:55.706789	["Hire two new developers"]	{"summary": "The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob", "decisions": ["Hire two new developers"], "actionItems": [{"task": "Prepare budget report", "owner": "Alice", "dueDate": "2026-04-25"}, {"task": "Send client proposal", "owner": "Bob", "dueDate": "2026-04-22"}]}	The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob	49
42	2026-04-18 16:07:45.411887	["Hire two new developers"]	{"summary": "The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob", "decisions": ["Hire two new developers"], "actionItems": [{"task": "Prepare budget report", "owner": "Alice", "dueDate": "2026-04-25"}, {"task": "Send client proposal", "owner": "Bob", "dueDate": "2026-04-22"}]}	The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob	50
43	2026-04-18 16:13:03.390607	["Hire two new developers"]	{"summary": "The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob", "decisions": ["Hire two new developers"], "actionItems": [{"task": "Prepare budget report", "owner": "Alice", "dueDate": "2026-04-25"}, {"task": "Send client proposal", "owner": "Bob", "dueDate": "2026-04-22"}]}	The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob	51
44	2026-04-18 16:21:43.732683	["Hire two new developers"]	{"summary": "The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob", "decisions": ["Hire two new developers"], "actionItems": [{"task": "Prepare budget report", "owner": "Alice", "dueDate": "2026-04-25"}, {"task": "Send client proposal", "owner": "Bob", "dueDate": "2026-04-22"}]}	The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob	52
45	2026-04-18 16:27:38.301409	["Hire two new developers"]	{"summary": "The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob for budget report and client proposal preparation", "decisions": ["Hire two new developers"], "actionItems": [{"task": "Prepare budget report", "owner": "Alice", "dueDate": "2026-04-25"}, {"task": "Send client proposal", "owner": "Bob", "dueDate": "2026-04-22"}]}	The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob for budget report and client proposal preparation	53
46	2026-04-18 17:37:42.191494	["Hire two new developers"]	{"summary": "The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob", "decisions": ["Hire two new developers"], "actionItems": [{"task": "Prepare budget report", "owner": "Alice", "dueDate": "2026-04-25"}, {"task": "Send client proposal", "owner": "Bob", "dueDate": "2026-04-22"}]}	The team discussed and decided on hiring new developers, and assigned tasks to Alice and Bob	54
47	2026-07-28 19:06:25.800354	["Ankit will complete the project documentation"]	{"summary": "Project documentation completion discussion", "decisions": ["Ankit will complete the project documentation"], "actionItems": [{"task": "Complete project documentation", "owner": "Ankit", "dueDate": "tomorrow"}]}	AI response parsing failed: Text 'tomorrow' could not be parsed at index 0	57
48	2026-07-28 19:13:15.907088	["Project documentation will be completed"]	{"summary": "Ankit will complete the project documentation", "decisions": ["Project documentation will be completed"], "actionItems": [{"task": "Complete project documentation", "owner": "Ankit", "dueDate": "2026-07-29"}]}	Ankit will complete the project documentation	58
49	2026-07-28 19:18:52.393961	["Project documentation completion"]	{"summary": "Ankit will complete the project documentation", "decisions": ["Project documentation completion"], "actionItems": [{"task": "Complete project documentation", "owner": "ankitp12160@gmail.com", "dueDate": "2026-07-29"}]}	Ankit will complete the project documentation	59
50	2026-07-28 19:42:20.42057	["Frontend completion assigned to Ankit"]	{"summary": "Ankit will complete the frontend work", "decisions": ["Frontend completion assigned to Ankit"], "actionItems": [{"task": "Complete frontend", "owner": "ankitp12160@gmail.com", "dueDate": "2026-07-29"}]}	Ankit will complete the frontend work	60
61	2026-09-13 20:35:17.839478	[]	{"summary":"Chirag has been assigned to review the code. The review is due by September 15, 2026. No other decisions were made.","decisions":[],"actionItems":[{"task":"review the code","owner":"Chirag","dueDate":"2026-09-15"}]}	Chirag has been assigned to review the code. The review is due by September 15, 2026. No other decisions were made.	72
63	2026-09-23 21:29:32.076878	["Fix notification service and deploy patch by 2026-09-25","Write post‑incident report by 2026-09-25"]	{"summary":"Chirag reported a critical bug causing failed payment notifications and committed to fixing and deploying the patch by 2026-09-25. Ankit agreed to draft a post‑incident report on the root cause, also due by 2026-09-25. Both emphasized the high priority of the task due to client urgency.","decisions":["Fix notification service and deploy patch by 2026-09-25","Write post‑incident report by 2026-09-25"],"actionItems":[{"task":"Fix notification service and deploy patch","owner":"chiragpokhariya2003@gmail.com","dueDate":"2026-09-25"},{"task":"Write post‑incident report documenting root cause","owner":"ankitchirag2003@gmail.com","dueDate":"2026-09-25"}]}	Chirag reported a critical bug causing failed payment notifications and committed to fixing and deploying the patch by 2026-09-25. Ankit agreed to draft a post‑incident report on the root cause, also due by 2026-09-25. Both emphasized the high priority of the task due to client urgency.	74
\.


--
-- Data for Name: meeting_participant_names; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.meeting_participant_names (meeting_id, name) FROM stdin;
72	Chirag
74	Chirag Pokhariya
74	Ankit Chirag
\.


--
-- Data for Name: meeting_participants; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.meeting_participants (meeting_id, email) FROM stdin;
1	ankit@gmail.com
1	bob@gmail.com
2	ankit@gmail.com
2	bob@gmail.com
3	ankit@gmail.com
3	bob@gmail.com
4	ankit@gmail.com
4	bob@gmail.com
5	ankit@gmail.com
5	bob@gmail.com
6	ankit@gmail.com
6	bob@gmail.com
7	ankit@gmail.com
7	bob@gmail.com
8	ankit@gmail.com
8	bob@gmail.com
9	ankit@gmail.com
9	bob@gmail.com
10	ankit@gmail.com
10	bob@gmail.com
11	ankit@gmail.com
11	bob@gmail.com
12	ankit@gmail.com
12	bob@gmail.com
13	ankit@gmail.com
13	bob@gmail.com
46	ankit@gmail.com
46	bob@gmail.com
47	ankit@gmail.com
47	bob@gmail.com
48	ankit@gmail.com
48	bob@gmail.com
49	alice@gmail.com
49	bob@gmail.com
50	alice@gmail.com
50	bob@gmail.com
51	alice@gmail.com
51	bob@gmail.com
52	alice@gmail.com
52	bob@gmail.com
53	alice@gmail.com
53	bob@gmail.com
54	alice@gmail.com
54	bob@gmail.com
55	alice@gmail.com
55	bob@gmail.com
56	ankit@gmail.com
56	priya@gmail.com
57	ankitp12160@gmail.com
58	ankitp12160@gmail.com
59	ankitp12160@gmail.com
60	ankitp12160@gmail.com
72	ankitchirag2003@gmail.com
74	chiragpokhariya2003@gmail.com
74	ankitchirag2003@gmail.com
\.


--
-- Data for Name: meetings; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.meetings (id, created_at, meeting_date, status, title, transcript, created_by) FROM stdin;
1	2026-04-16 04:50:26.770967	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
2	2026-04-16 04:58:06.526769	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
3	2026-04-16 04:58:53.78896	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
4	2026-04-16 05:03:13.034366	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
5	2026-04-16 10:17:35.792307	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
6	2026-04-16 10:26:58.94526	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
7	2026-04-16 10:34:09.648603	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
8	2026-04-16 10:40:50.507471	2026-04-15 10:00:00	PENDING	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
9	2026-04-16 17:36:35.70706	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
10	2026-04-16 18:01:01.835914	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
11	2026-04-16 18:07:51.939887	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
12	2026-04-16 18:14:41.404373	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
13	2026-04-16 18:18:49.963658	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
46	2026-04-18 15:44:18.734838	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
47	2026-04-18 15:48:41.23044	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
48	2026-04-18 15:56:09.600077	2026-04-15 10:00:00	ANALYZED	Q2 Planning Meeting	Ankit discussed the Q4 budget. Bob will prepare the financial report by April 20th. Alice needs to send the client proposal by April 18th. Team decided to increase marketing spend.	1
49	2026-04-18 16:00:25.405023	2026-04-18 10:00:00	ANALYZED	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	1
50	2026-04-18 16:07:30.682137	2026-04-18 10:00:00	ANALYZED	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	1
51	2026-04-18 16:12:45.193583	2026-04-18 10:00:00	ANALYZED	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	1
52	2026-04-18 16:21:27.793436	2026-04-18 10:00:00	ANALYZED	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	1
53	2026-04-18 16:27:20.487044	2026-04-18 10:00:00	ANALYZED	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	2
54	2026-04-18 17:37:23.110992	2026-04-18 10:00:00	ANALYZED	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	2
55	2026-06-25 05:38:13.966153	2026-04-18 10:00:00	PENDING	Test Meeting	Alice will prepare the budget report by 2026-04-25. Bob will send the client proposal by 2026-04-22. Team decided to hire two new developers.	2
56	2026-06-25 05:46:13.006554	2026-04-20 10:00:00	PENDING	Product Launch Planning	Ankit will design the landing page by April 28th. Priya will coordinate with the marketing team by April 25th. Team decided to launch the product on May 1st. Rahul will prepare the demo video by April 30th.	1
57	2026-07-28 19:05:19.455583	2026-06-26 10:00:00	ANALYZED	Email Test Meeting	ankitp12160@gmail.com will complete the project documentation by tomorrow.	3
58	2026-07-28 19:12:53.815383	2026-06-26 10:00:00	ANALYZED	Email Test Meeting	ankitp12160@gmail.com will complete the project documentation by 2026-07-29.	3
59	2026-07-28 19:18:27.270521	2026-06-26 10:00:00	ANALYZED	Email Test Meeting	ankitp12160@gmail.com will complete the project documentation by 2026-07-29.	3
60	2026-07-28 19:41:45.017368	2026-06-26 10:00:00	ANALYZED	Email Test Meeting	ankitp12160@gmail.com will complete the frontend by 2026-07-29.	3
72	2026-09-13 20:34:59.627149	2026-09-12 10:00:00	ANALYZED	Email Reminder Test	Chirag will review the code by 2026-09-15.	3
74	2026-09-23 21:28:42.937542	2026-09-24 15:00:00	ANALYZED	Client Escalation Review	Chirag raised a critical bug reported by the client regarding failed payment notifications. He committed to fixing the notification service and deploying the patch by September 25, 2026. Ankit agreed to write the post-incident report documenting the root cause and will complete it by September 25, 2026 as well. Both agreed this is high priority given the client's urgency.	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, created_at, email, full_name, password, is_approved, role) FROM stdin;
3	2026-07-28 19:02:45.810783	ankitp12160@gmail.com	Ankit Singh	$2a$10$iyCoL1SOW.UqTh9ENCmxzOD0UqVIj/J9OBhkWSskmQO7sLZFfaARG	t	ADMIN
2	2026-04-18 16:26:31.304172	test2@gmail.com	Test User 2	$2a$10$w25gCECIRD3xE5e/2srooOf.FG1YMWreXDoLNbglDAawhHd/M/UZq	f	USER
1	2026-04-16 04:49:02.32079	test@gmail.com	Test User	$2a$10$HGlbazIDNSXY3EOhsMKire/axodfYEFL0rV2Q/Vdmj.0uQO2g50l6	t	USER
\.


--
-- Name: action_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.action_items_id_seq', 91, true);


--
-- Name: meeting_insights_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.meeting_insights_id_seq', 63, true);


--
-- Name: meetings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.meetings_id_seq', 74, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: action_items action_items_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.action_items
    ADD CONSTRAINT action_items_pkey PRIMARY KEY (id);


--
-- Name: meeting_insights meeting_insights_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meeting_insights
    ADD CONSTRAINT meeting_insights_pkey PRIMARY KEY (id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: meeting_insights uk6oogdofdtcfnr1yk2a4bspjqr; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meeting_insights
    ADD CONSTRAINT uk6oogdofdtcfnr1yk2a4bspjqr UNIQUE (meeting_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: meeting_participant_names fk1g1ym3oiwufmqnrcnyvyhjfql; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meeting_participant_names
    ADD CONSTRAINT fk1g1ym3oiwufmqnrcnyvyhjfql FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- Name: meeting_participants fk7uds89kvog9etbdnn653vsf6y; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT fk7uds89kvog9etbdnn653vsf6y FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- Name: meetings fk91iiqwhms7obbc92so3wxqq6f; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fk91iiqwhms7obbc92so3wxqq6f FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: action_items fk951rvnn7q6smrdbtc2h5phfbw; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.action_items
    ADD CONSTRAINT fk951rvnn7q6smrdbtc2h5phfbw FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- Name: meeting_insights fkifww5ty5bflutx1n1a7jxfkgg; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.meeting_insights
    ADD CONSTRAINT fkifww5ty5bflutx1n1a7jxfkgg FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- PostgreSQL database dump complete
--

\unrestrict rNREQXNhfBoDOwk8bE8Fm5xNfanCb60wPSevDORxiyAqchmCNycbuX2fpyYkjjs

